### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#17] opened 2017-01-11 08:48 UTC
- Below is the display of message when the api returns empty data. This is the same for both sent and inbox items.

![user_image_6](https://cloud.githubusercontent.com/assets/23191755/21841572/bad0f59c-d808-11e6-8418-10e5f1851262.JPG)

**Comment by shastri9999** [comment] 2017-01-26 20:32
@suneelng Can you give me the user you logged in with, because if I programatically set empty messages for component to test this scenario, this is not reproducible.

**Comment by shastri9999** [comment] 2017-01-29 06:05
I tried to reproduce by setting manually but issue was not reproducible, as per suneel's suggestion tried creating a new user who will have empty inbox and sent messages

So tested with kyckuser@mailiantor.com (password: test1234). Here are screenshots

![screen shot 2017-01-29 at 11 35 24 am](https://cloud.githubusercontent.com/assets/876778/22402292/142062e2-e617-11e6-87f9-55abea7fd1d4.png)


This is not reproducible, so closing.

**Comment by suneelng** [comment] 2017-02-04 04:00
@shastri9999 
- The issue still appears
- Below is the screen shot.
- Kindly use "http://ec2-54-169-44-116.ap-southeast-1.compute.amazonaws.com/", 
un: suneel@appcleus.com, test123


![image](https://cloud.githubusercontent.com/assets/23191755/22615549/937eb8d2-eabc-11e6-997b-ea1e39f8dcbb.png)

**Comment by shastri9999** [comment] 2017-02-04 06:34
@suneelng Fixed in commit 2f2a1b3 . 
The issue was with other user I tested data in messages returned empty array. In this case it returns a string like "No messages ... " , the data was treated like an array and iteration happened over string. Fixed with additional type check before iteration.

**Comment by suneelng** [comment] 2017-02-07 17:06
@shastri9999 
- Thanks for identifying the response message, i will fix the back end as well.
- Could you please verify if this check is taken care on the dashboard page, as i saw a similar behavior on the latest commit.

**Comment by shastri9999** [comment] 2017-02-10 16:56
Verified and fixed.

**Closed as completed** 2017-02-10 16:56 UTC
